version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=./resourcehub.db
      - SESSION_SECRET=your-super-secure-session-secret-change-this
      - UPLOAD_DIR=./uploads
      - MAX_FILE_SIZE=104857600
    volumes:
      # Mount database and uploads as volumes for persistence
      - ./data/resourcehub.db:/app/resourcehub.db
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
  uploads: